export const enPages = {
    home: {
      awardsEyebrow: "Awards and Commendations",
      awardsTitle: "Awards and Commendations",
      recommendationsEyebrow: "Recommendations",
      recommendationsTitle: "Professional Recommendations",
      impactEyebrow: "Key Achievements",
      impactTitle: "Numbers that show system scale, not only years of experience",
      impactDescription: "Indicators tied to real projects and platforms, showing operational scale, reach, and impact.",
      projectsEyebrow: "Featured Projects",
      projectsTitle: "Selected Projects",
      projectsDescription: "Independent cards for major national and enterprise projects, showing organization, role, technologies, and business impact in a consistent format.",
      careerEyebrow: "Professional Journey",
      careerTitle: "From technical and academic work to government platforms",
      careerDescription: "Experience developed across education, training, industry, the private sector, the Ministry of Interior, and the Ministry of Digital Transformation and Telecommunications.",
      trustLabel: "Executive Trust Indicator"
    },
    about: { title: "Professional Profile", description: "The professional profile of Abubaker Altaif as a Product Architect and Digital Transformation Lead.", heroTitle: "Building systems from problem understanding to stable operations", heroDescription: "A path combining statistics, computer science, business analysis, product architecture, team establishment, and measurable government and enterprise platform operations.", body1: "I build enterprise systems and digital products, with a background combining statistics, computer science, and hands-on experience turning manual or fragmented operations into usable, measurable, and scalable digital systems.", body2: "The journey started with academic and training systems, then evolved into national information system projects, industrial and enterprise systems, high-volume government digital services, and technical leadership for Baldna Platform for government data and transaction exchange. Across these roles, the work included needs analysis, system design, building or leading the first usable versions, establishing teams, and supporting rollout and stability.", capabilitiesEyebrow: "Core Capabilities", capabilitiesTitle: "Professional Capabilities", capabilities: [["Turning complexity into operable systems", "Reengineering operational procedures and legacy systems into scalable digital products."], ["Enterprise solution engineering", "Connecting business requirements with stable technical architecture and performance indicators that support management decisions."], ["Leadership and capability building", "Establishing technical and operations teams and the working procedures needed to keep systems running after launch."]] },
    experience: { title: "Professional Experience", description: "Professional experience connected to digital products, government platforms, and enterprise systems.", heroTitle: "Professional experience across government, industry, education, and the private sector", heroDescription: "Each role highlights responsibilities and projects that built capacity in digital transformation and product engineering." },
    projects: { title: "Featured Projects", description: "Case studies for government and enterprise projects documented through roles, results, and numbers.", heroTitle: "National and enterprise projects documented by impact", heroDescription: "Each card presents the project name, organization, period, overview, role, key technologies, and impact in a consistent format." },
    expertise: { title: "Areas of Expertise", description: "Digital value engineering framework and technical and managerial areas of expertise.", heroTitle: "A professional framework that starts with business and ends with improvement", heroDescription: "The digital value engineering approach connects understanding, analysis, and design with building, measurement, and continuous improvement.", relatedTitle: "Areas of Expertise", skillsTitle: "Skills", keywordsTitle: "Keyword Groups by Area" },
    awards: { title: "Awards and Commendations", description: "Awards, official commendations, and professional recommendations tied to documented projects and organizations.", heroTitle: "Awards and Commendations", heroDescription: "Awards, thank-you letters, certificates of appreciation, and official commendations linked to projects, organizations, and years.", awardsTitle: "Awards and Commendations", recommendationsTitle: "Professional Recommendations" },
    recommendations: { title: "Recommendations", description: "Professional recommendations and certificates from educational, government, and industrial organizations.", heroTitle: "Professional Recommendations", heroDescription: "Recommendation letters and service certificates tied to an organization, date, and documented work." },
    education: { title: "Education and Certificates", description: "Academic qualifications and documented professional courses.", heroTitle: "An academic foundation combining statistics and computer science", heroDescription: "This combination of data and computing shaped the way complex systems are analyzed and measurable products are built." },
    contact: { title: "Contact", description: "Direct contact channels and resume files for Abubaker Altaif.", heroTitle: "Contact Information", heroDescription: "Direct contact channels and professional collaboration areas in enterprise systems building, digital product architecture, and digital transformation delivery from design to stable operations.", availableTitle: "Professional Collaboration Areas" },
    ats: { title: "ATS Resume", description: "A structured text version of Abubaker Altaif's resume prepared for applicant tracking systems.", impact: "Impact", experience: "Experience", projects: "Selected Projects" },
    resumePdf: { title: "Resume PDF", description: "Download the resume in PDF format.", heroTitle: "Resume in PDF Format", heroDescription: "A downloadable copy of the resume attached to the project." }
  };
